services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: green-api-backend
    ports:
      - "5050:5050"
    environment:
      APP_CONFIG: /app/config/config.yaml
    volumes:
      - ../config/config.yaml:/app/config/config.yaml:ro
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: green-api-frontend
    depends_on:
      - backend
    ports:
      - "5000:5000"
    restart: unless-stopped
